mount/mount.go

Since this is a new library, we are free to remove the deprecated
functions. Fortunately, there's only one.

mount: rm ForceMount

---

mountinfo/go.mod

This module is not dependent on any other modules, so it needs to be
added first.
Once added, we can do the same for `moby/sys/mount`

mountinfo: add go.mod

---

mount/go.mod
mount/go.sum

The version of golang.org/x/sys corresponds to the one currently used
by Moby.
Once there, it needs to be tagged, e.g.
```
git tag mount/v0.1.0
```

mount: add go.mod

---

mount/mount_unix_test.go
mount/mounter_linux_test.go
mount/sharedsubtree_linux_test.go

The mount option `relatime` can be added by the kernel, and
this is what happens on my machine:
> --- FAIL: TestMount (0.00s)
>     mounter_linux_test.go:176: unexpected mount option "relatime", expected ""
> FAIL
Same as in commit afc7b0dd970, this option should be ignored.
1. Do not ignore errors from Mkdir.
2. Use ioutil.WriteFile for simplicity, to not leak fds and to not
ignore errors from Write or Close.

mount: test nitpicks

---

.github/workflows/test.yml
Makefile

Run unit tests and golangci-linter (with default config for now).
This actually uncovers a bug in mount package for windows, yay!

Add CI based on github actions

---

mount/mount.go
mount/mount_errors.go

This is only used for !windows, so move this to a separate
source file to avoid the following windows linter warning:
> ##[error]mount.go:14:6: type `mountError` is unused (unused)
This is just moving stuff around, no functional change

mount: separate mount error wrapper

---

mountinfo/mountinfo_linux_test.go

TIL older kernels (presumably < 5.1) has a bug of not showing
the "source" field in /proc/self/mountinfo in case an empty
string was passed as the source argument to mount() syscall.
My best guess is it was fixed by the kernel commit 8f2918898eb5f
("new helpers: vfs_create_mount(), fc_mount()", Nov 4 2018) which
is `v5.1-rc1~12^2~37`, i.e. kernel 5.1 should be the one with the fix.
I was able to reproduce it on a machine with an old kernel:
```console
[kir@micros ~]$ cat a.c
#include <sys/mount.h>
#include <stdio.h>
int main(void) {
int r;
r = mount("", "/tmp/bb", "tmpfs", MS_MGC_VAL, (void*)0);
if (r != 0) {
perror("mount");
return 1;
}
return 0;
}
[kir@micros ~]$ gcc -Wall -o a a.c
[kir@micros ~]$ mkdir /tmp/bb
[kir@micros ~]$ ./a; echo $?
mount: Operation not permitted
1
[kir@micros …
```

mountinfo: add "empty source" test case

---

mountinfo/mountinfo.go

Some code have tests or benchmarks that come with fake mountinfo.
To switch those to use moby/sys/mountinfo without any major rework
of those tests and benchmarks we need to provide a way to work
with such fake mountinfo.
This is probably more important for benchmarks, since without
this we can't make any comparisons after switching to moby/sys.

mountinfo: add GetMountsFromReader

---

mountinfo/mountinfo_filters.go
mountinfo/mountinfo_freebsd.go
mountinfo/mountinfo_linux.go

Make `Source` and `VfsOpts` available to filters.
Cgroup parsing code in opencontainers/runc may benefit.
Update the docs accordingly.

More fields for filters

---

mountinfo/mountinfo_unsupported.go
mountinfo/mountinfo_windows.go

When compiling for windows, we get this error:
> GOOS="windows" GOARCH="amd64" GOARM=""
> vendor/github.com/moby/sys/mountinfo/mountinfo.go:16:9: undefined: parseInfoFile
The problem is newly added GetMountsFromReader() (see https://github.com/moby/sys/pull/6)
Amend the `_windows.go` and `_unsupported.go` to fix.
NOTE that eventually we need to deprecate windows support for this
library, since it's not really doing anything.

mountinfo: fix windows build

---

mount/mount_unix_test.go
mountinfo/mountinfo_test.go

Excluding darwin, as these packages don't support it, but a developer may try running the tests on a Mac.

Exclude macOS (darwin)

---

mountinfo/mountinfo_linux.go
mountinfo/mountinfo_linux_test.go

Moby PR https://github.com/moby/moby/pull/38977 and containerd PR https://github.com/containerd/containerd/pull/3159
added the handing of escape sequences in mountinfo paths (root and mountpoint fields).
Unfortunately, it also broke the handling of paths containing double
quotes, as it was pointed out in https://github.com/containerd/containerd/issues/4257
The solution is to stop using strconv.Unquote and write our own
specialized function to deal with escape sequences.
Unit tests added.
In addition, unescape the fstype and source fields (the first two after the `-` separator, since kernel escapes those as well.

mountinfo: fix path unescaping

---

mountinfo/mountinfo_test.go

Apparently, Ubuntu build system is some sort of a chroot which does not
have `/` mount in its /proc/self/mountinfo. This leads to test failure
described in https://github.com/moby/sys/issues/17.
The fix is not to require a specific mount (even `/` that must exist but
apparently does not in some setups). Instead, let's require at least 2
mounts, doesn't matter which ones.
For reference, his test case was added by
https://github.com/moby/moby/pull/4812
Fixes:  https://github.com/moby/sys/issues/17

mountinfo/TestGetMounts: fix for Ubuntu build system

---

Makefile

Changes: https://github.com/golangci/golangci-lint/releases
(I am not using 1.27.0 as it has a windows installation bug: golangci/golangci-lint#1202)

ci: update golangci-lint to 1.26.0

---

mountinfo/go.mod
mountinfo/go.sum
mountinfo/mountinfo.go
mountinfo/mountinfo_unix.go
mountinfo/mountinfo_unsupported.go
mountinfo/mountinfo_windows.go

Add two fast paths to avoid (slow) mountinfo parsing:
1. In case path does not exist, it is definitely NOT a mount point.
2. In case path's `st.Dev` differs from that of its parent, it is
definitely a mount point.
In all the other cases (including bind mounts, case of `path="/"`, other
errors from `unix.Lstat`) the code falls back to the old slow method
of parsing mountinfo.

mountinfo.Mounted: optimize by adding fast paths

---

mount/mount.go
mount/unmount_unix.go
mount/unmount_unsupported.go

In many cases, this is called with an argument that is a mount point
itself. In such case, if we're on Linux, MNT_DETACH ensures that the
umount is recursive (which is its nice, but a little known feature).
For other platforms, if the mount does not have any submounts
underneath and is not busy, it will be unmounted.
In the above case, we no longer have to parse mountinfo and perform
the unmounts one-by-one.
IOW this should speed up RecursiveUnmount() for some cases, without
breaking the compatibility.
While at it
- fix a typo in doc;
- add that the argument does not have to be a mount point;
- improve mount.Unmount doc.
Fixes: https://github.com/moby/sys/issues/21

mount.RecursiveUnmount: add a fast path

---

mount/flags_freebsd.go
mount/flags_unsupported.go
mount/go.mod
mount/go.sum

Bump `golang.org/x/sys/unix` to the latest version and use the `MNT_*`
constants defined there instead of getting them from `sys/mount.h` using
cgo.
Full diff for the `golang.org/x/sys/unix` bump: https://github.com/golang/sys/compare/d5e6a3e2c0ae...aee5d888a86055dc6ab0342f9cdc7b53aaeaec62

mount: use MNT_* flags from golang.org/x/sys/unix on freebsd

---

mountinfo/mountinfo.go
mountinfo/mountinfo_linux.go
mountinfo/mountinfo_linux_test.go
mountinfo/mountinfo_unsupported.go
mountinfo/mountinfo_windows.go

... as no other platform provides something like /proc/self/mountinfo.
Closes: https://github.com/moby/sys/pull/38
Closes: https://github.com/moby/sys/pull/35
@thaJeztah PTAL

mountinfo: make GetMountinfoFromReader Linux-specific

---

Makefile

Changes: https://github.com/golangci/golangci-lint/releases

ci: update golangci-lint to 1.31.0

---

Makefile
mount/flags_bsd.go
mount/mount_unix_test.go
mount/mounter_bsd.go
mount/mounter_linux_test.go
mount/mounter_unsupported.go
mount/sharedsubtree_linux_test.go
mountinfo/doc.go
mountinfo/mounted_unix.go
mountinfo/mountinfo_bsd.go
mountinfo/mountinfo_linux.go
mountinfo/mountinfo_linux_test.go
mountinfo/mountinfo_unsupported.go

I am looking at using these modules in containerd, so that we can
reduce the effort of maintaining "mountinfo" implementations.
The containerd variant of this module currently supports OpenBSD in
addition to FreeBSD.
This patch bring in changes similar to the ones made in containerd in:
https://github.com/containerd/containerd/commit/0828b7aa96b55e36a9594e3b98a3f6800bc0734a

Add support for OpenBSD in addition to FreeBSD

---

mountinfo/mountinfo.go
mountinfo/mountinfo_bsd.go
mountinfo/mountinfo_filters.go
mountinfo/mountinfo_linux.go
mountinfo/mountinfo_linux_test.go

follow-up to https://github.com/moby/sys/pull/32
I am looking at using these modules in containerd, so that we can reduce the effort of maintaining "mountinfo" implementations.
This change renames the info fields to match the ones used in containerd, which are more "correct" from a Go naming perspective: https://github.com/containerd/containerd/commit/8cd218237b49b41bffa0035393143571ec01b157
This will be a breaking changes for consumers of this package, but we're still pre-v1.0.0, so if we want to make these changes, this is still possible now.

mountinfo: use idiomatic naming for fields

---

mountinfo/mountinfo_filters.go
mountinfo/mountinfo_linux_test.go

This is a followup to #34.
Rename FstypeFilter -> FSTypeFilter.
Also, fix the FilterFunc doc.
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>

mountinfo: rename FstypeFilter -> FSTypeFilter

---

mount/go.mod
mount/go.sum
mount/mounter_linux_test.go

mount: bump mountinfo to v0.3.1

---

mount/mount_unix.go

- calculate "last mount" outside of the loop
- omit empty "sub-errors" in error message

mount.RecursiveUnmount(): minor improvements

---

mountinfo/doc.go
mountinfo/mountinfo_filters.go

1. Lines that start with a space are treated as verbatim text
(rendered as \<pre\> in HTML). Fix those.
2. There is no sense in having github markdown (like `var`).
This was inspired by the way it looks right now:
* https://pkg.go.dev/github.com/moby/sys/mountinfo@v0.3.1

mountinfo: doc fixes

---

mountinfo/mountinfo_linux.go

Function PidMountInfo is not named correctly (it should be PID not Pid,
and we already have mountinfo in the package name so it's tautological),
and can not accept FilterFunc.
Besides, there are not too many users of this function (I was only able
to found one, see [1]) and users can switch to GetMountsFromReader.
Depreate this function. The plan is to remove it before v1.0.
[1] https://github.com/DataDog/datadog-agent/pull/6495/commits/406d98801434dedc87cab6195079f735d6903d48

mountinfo: deprecate PidMountInfo

---

mountinfo/mountinfo_filters.go
mountinfo/mountinfo_linux.go
mountinfo/mountinfo_linux_test.go

This fixes two correctness issues with mountinfo (one of which caused opencontainers/runc#2647 to be a security regression):
* Correctly handle IO errors during scanning.
* Run the filter function after all fields are parsed.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

mountinfo: correctness improvements

---

Makefile
symlink/LICENSE.APACHE
symlink/LICENSE.BSD
symlink/README.md
symlink/doc.go
symlink/fs.go
symlink/fs_unix.go
symlink/fs_unix_test.go
symlink/fs_windows.go
symlink/go.mod
symlink/go.sum

replaces https://github.com/moby/sys/pull/53
closes https://github.com/moby/sys/pull/53
relates to https://github.com/containerd/containerd/pull/4631
Strategy taken:
```bash
cd ~/projects
git clone https://github.com/docker/docker.git moby_symlink
cd moby_symlink
git checkout -b migrate_pkg_symlink
git filter-repo --path pkg/symlink
cd ~/projects/moby-sys
git checkout -b integrate_moby_symlink
git remote add moby_symlink ~/projects/moby_symlink
git fetch moby_symlink
git merge --allow-unrelated-histories --signoff -S -Xsubtree=pkg/ moby_symlink/migrate_pkg_symlink
```
After the above;
- symlink: remove "github.com/docker/docker" import enforcement comments
- symlink: add go.mod
- Makefile: run tests on symlink module
- symlink: add package doc

Migrate github.com/docker/docker/pkg/symlink

---

mountinfo/mountinfo.go
mountinfo/mountinfo_linux.go

1. Add a "custom file" use case to GetMountsFromReader.
2. Remove obsoleted old comment from parseMountTable.
Refresh documentation about mountinfo.Info fields, based on the latest
proc(5) from man-pages v5.08.

mountinfo: docs nits

---

mount/mounter_freebsd.go
mount/mounter_openbsd.go

This is made for the sysutils/docker-cli port which I maintain, as moby/sys is part of the vendored libraries for docker/cli.
While I could stub this out (the same way as how it is on darwin and windows), I decided to actually write a proper mounter since it seems there's intention to actually bring OpenBSD support (as seen in https://github.com/moby/sys/commit/cb807b1e4cf01065587739df73d758d6d171819b).
OpenBSD's [mount(2)](https://man.openbsd.org/mount.2) works differently since it uses separate structs to present options for different filesystems, unlike in FreeBSD. It also means that support for other filesystems need to be added explicitly. I'm not sure which ones are required for now so I just write support for only FFS, which is the go-to filesystem used by OpenBSD systems.

Create proper mounter for OpenBSD

---

symlink/fs_unix_test.go
symlink/go.mod

Cleanup was added in Go 1.14, so we need to drop go 1.13 for this.

symlink: drop go 1.13, and use testing.Cleanup()

---

mount/mount_unix_test.go
mount/mounter_linux_test.go

Carrying the pkg/mount changes from https://github.com/moby/moby/pull/36720

mount: add exec and noexec as valid flags to mount options

---

mountinfo/mountinfo_filters.go
mountinfo/mountinfo_filters_test.go

The PrefixFilter matched on a literal "prefix", making it too greedy, and,
for example, filtering on "/a" prefix would also return mounts for
"/aaa" or "/abc".
This patch changes the matching to match on a prefix / parent _path_ instead.

mountinfo: fix PrefixFilter() being too greedy

---

mount/go.mod
mount/go.sum
mount/mount_unix_test.go

1. Bump mountinfo to v0.4.1
2. Add `TestRecursiveUnmountTooGreedy` (failing with 0.4.0, passing with 0.4.1, thanks to #61)
3. Fix temp dir creation
~~this is currently a draft pending https://github.com/moby/sys/pull/61 merge and a version bump~~

mount: bump mountinfo to 0.4.1, add TestRecursiveUnmountTooGreedy test

---

Makefile
signal/go.mod
signal/go.sum
signal/signal.go
signal/signal_darwin.go
signal/signal_freebsd.go
signal/signal_linux.go
signal/signal_linux_mipsx.go
signal/signal_linux_test.go
signal/signal_test.go
signal/signal_unix.go
signal/signal_unsupported.go
signal/signal_windows.go

same as https://github.com/moby/sys/pull/69, but from https://github.com/moby/moby/pull/42641 (not yet merged)
relates to https://github.com/containerd/containerd/issues/5402
Migrating this package from commit (https://github.com/moby/moby/pull/42641):
https://github.com/docker/docker/commit/9a6ff685a80639995311c0572d662360b55796d9
Strategy taken:
cd ~/projects
git clone https://github.com/docker/docker.git moby_signal
cd moby_signal
git filter-repo  --path pkg/signal --path-rename pkg/signal:signal
git filter-repo --path-glob 'signal/*.md' --path-glob 'signal/*_deprecated.go' --invert-paths
cd ~/projects/moby-sys
git checkout -b integrate_moby_signal_take2
git remote add moby_signal ~/projects/moby_signal
git fetch moby_signal
git merge …

migrate github.com/docker/docker/pkg/signal (take 2)

---

signal/signal_windows.go

We'd like to use moby/sys/signal in containerd, but containerd currently
supports more signals. Adding them here closes the gap.
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>

Handle more signals to make ParseSignal containerd compatible

---

signal/signal_darwin.go

I noticed that the name for `SIGBUS` on Darwin was mapped to `BUG`. To be sure that a `BUG` signal is not actually a "thing", I looked at the history for this; this mapping was originally added in: https://github.com/docker/docker/commit/10dc16dcd3aa82be256e5072a25dcf18af8e3844 (https://github.com/docker/docker/pull/4563),
Looking at the Darwin headers, I also don't see a mention of a `BUG` signal:
https://github.com/apple/darwin-xnu/blob/b6dbbb99918752ac84da97aa9b473bd974afc609/bsd/sys/signal.h#L98,
So, I'm assuming this was a rather funny slip-up, which makes this a "BUS-FIX" ?

signal: fix name for SIGBUS on darwin

---

signal/signal_freebsd.go

I'm guessing this was a typo; originally added in:
https://github.com/docker/docker/commit/10dc16dcd3aa82be256e5072a25dcf18af8e3844,
(Assuming the author has a dislike for SIGBUS (or 🚌))

signal: fix name for SIGBUS on freebsd

---

signal/signal_windows.go

Keeping the list in the same order as the other platforms.

signal: sort Windows signals alphabetically

---

signal/signal_unix.go
signal/signal_windows.go

relates to https://github.com/moby/moby/pull/42717
This const was inherited from the Docker/Moby repository, but does not make a lot of sense in the new location.
Removing this const here.

signal: remove DefaultStopSignal

---

mount/flags_unix.go

looks like I missed this one when opening https://github.com/moby/sys/pull/75

mount: errors should not start with a capital

---

mountinfo/mountinfo_linux.go

We expect 2 fields to be there, anything below (or above) will produce
an error, so limit the number of strings we split into to 3. This still
allows us to detect "too many colons", but won't result in splitting
without bounds.

mountinfo.GetMountsFromReader() use strings.SplitN()

---

mountinfo/mountinfo_linux.go
mountinfo/mountinfo_linux_test.go

This switch was implementing the exact same check as is done in
strings.Join(); https://cs.opensource.google/go/go/+/refs/tags/go1.16.7:src/strings/strings.go;l=421-427
```go
func Join(elems []string, sep string) string {
switch len(elems) {
case 0:
return ""
case 1:
return elems[0]
}
```
This only difference removing this switch makes is that it will assign
an empty string to p.Optional if no optional fields are present, but
given that an empty string is the default value for p.Optional, this
should make no difference.
This also revealed an off-by-one bug:
Before this change:
- we return an error if `sepIdx == 5` (earlier check)
- for `sepIdx == 6` we skipped (in this switch)
- for `7`, we take field 6 (equivalent to `fields[6:7]`, or `fields[6:sepIdx]`)
- for the "default" (else), we …

mountinfo: GetMountsFromReader() remove redundant switch, fix dropped "optional" fields

---

mountinfo/mounted_linux_test.go

This updates the test to only skip the mountedByOpenat2() part, instead
of skipping the whole test, if openat2 is not supported.

TestMountedBy: skip mountedByOpenat2() check if not supported

---

.github/workflows/test.yml

go 1.15 is no longer supported, and go 1.14 is not supported since go
1.16 is released (roughly half a year ago).
Let's keep the latest unsupported version (1.15) for now, but drop the
older 1.14.

ci/gha: drop go 1.14, add go 1.17

---

mountinfo/mounted_linux.go
mountinfo/mounted_linux_test.go
mountinfo/mounted_unix.go
mountinfo/mountinfo.go
mountinfo/mountinfo_bsd.go

Fix Mounted() and its tests.
1. In case the argument does not exist, Mounted now returns an
appropriate error. Previously, this condition was treated as
"not a mount point", with no error returned, but in fact such
path could be a mount point, overshadowed by another mount.
Since the mount is still unreachable, it can not be unmounted
anyway, so we do not fall back to `mountedByMountinfo`, returning
an error instead.
⚠️ In case callers are not interested in `ENOENT`, they should filter it
out. Amend the function doc accordingly.
2. There are some corner cases in which `mountedByOpenat2` or `mountedByStat`
do not work properly. In particular,
- neither work if there's an ending slash;
- neither work for a symlink to a mounted directory;
- `mountedByStat` do not work a parent of path is a …

mountinfo.Mounted(): fix

---

.gitattributes
.golangci.yml
Makefile
mount/mount_unix.go
mount/mount_unix_test.go
mount/mounter_linux.go
mount/sharedsubtree_linux_test.go
mountinfo/mounted_linux.go
mountinfo/mountinfo_linux_test.go
symlink/fs_unix_test.go
symlink/fs_windows.go

~~_(currently a draft pending #90 merge)_~~
* Enable some linters, fix their warnings.
* Update golangci-lint to 1.43.0.
* Force LF line endings for .go files.
Fixes: #91

CI: add more linters

---

mount/mount_errors.go
mount/mounter_unsupported.go

Since commit 7a521626bc899dc Mount is not implemented on Darwin, so
mount() is left unused.
Also, mount errors are only used from mount(), and thus are not used on
Darwin.
This fixes a bunch of warnings from "unused" and "deadcode" lints.
Alas, those warnings did not result in CI failures on Mac; see https://github.com/moby/sys/issues/99

mount: fix unused/deadcode warnings on Mac

---

mountinfo/mounted_linux.go
mountinfo/mounted_linux_test.go
mountinfo/mountinfo.go

This is a carry of #97 -- mostly the same code, arranged slightly differently. I have also cleaned up tests a bit.
@manugupt1 PTAL

mountinfo: add MountedFast

---

Makefile

Apparently GHA CI Mac OS X environment uses old GNU Make (v3.81) which
does not yet support `.SHELLFLAGS` (added by commit 8589e2e7).
Since we call a few commands (under `for`) from the make target,
intermediate failures are ignored unless `-e` shell option is set (or
explicit `&&` is used, which is not possible to do in `for`).
Example:
```sh
for cmd in false true; do $cmd; done
```
will succeed unless `set -e` is set, because the last command executed is `true` and its exit code is `0`.
To fix, use explicit `set -e` where we execute more than a single command.
Also, replace `&&` with `;` for multiple commands. Technically this is not
required for the fix, but since having `set -e` results in implicit `&&` everywhere,
there is no need to have `&&` explicitly. In other words, this change …

Makefile: rm .SHELLFLAGS, add set -e

---

mount/mount_unix_test.go
mount/mounter_linux_test.go
mount/sharedsubtree_linux_test.go

- use `t.TempDir`
- use `os.WriteFile` instead of `ioutil.WriteFile`
- remove `createFile`

mount: trivial test nitpicks

---

mountinfo/mounted_unix.go

While trying to import MountedFast into k8s to detect mount points
using openat2, several tests failed because they rely on
os.IsErrNotExist / os.IsPermission which do not actually test the
underlying error.
For a non-existent path, if we return the bare error, this problem
is solved. I tested for the following cases to ensure that
backward compatibility is not broken:
````
fmt.Println(os.IsNotExist(err)) returns false
fmt.Println(os.IsNotExist(&os.PathError{
Op:   "lstat",
Path: "somepath",
Err:  err,
})) returns false
fmt.Println(os.IsNotExist(fmt.Errorf("unable: %w", err))) returns false
fmt.Println(errors.Is(fmt.Errorf("unable: %w", err), os.ErrNotExist))
returns true.
```
cc @kolyshkin @thaJeztah

Do not wrap errors from filepath / os as they are already wrapped.

---

mount/mount_unix_test.go

Add test for RecursiveUnmount when a submount fails to unmount.
https://github.com/moby/sys/issues/45
Signed-off-by: Manu Gupta <manugupt1@gmail.com>

Add test for RecursiveUnmount when a submount fails to unmount.

---

.github/workflows/test.yml
Makefile

See individual commits for details.

ci: add go 1.18, drop 1.16

---

mount/go.mod
mount/go.sum
mountinfo/go.mod
mountinfo/go.sum
signal/go.mod
signal/go.sum
symlink/go.mod
symlink/go.sum

Includes fixes for:
- CVE-2022-29526 (http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-29526);
(description at https://go.dev/issue/52313).
full diff: https://github.com/golang/sys/compare/69cdffdb9359ff97d91e4f4fbb6b2714c3898eae...33da011f77ade50ff5b6a6fb4a9a1e6d6b285809

update golang.org/x/sys v0.0.0-20220412211240-33da011f77ad

---

mountinfo/mounted_unix.go
mountinfo/mountinfo_bsd.go
mountinfo/mountinfo_freebsdlike.go
mountinfo/mountinfo_openbsd.go
mountinfo/mountinfo_unsupported.go

Alternative PR for https://github.com/moby/sys/pull/113

mountinfo: BSDs no longer need cgo nor reflect

---

mountinfo/mounted_linux.go
mountinfo/mountinfo.go

There are two nits:
1. Since go 1.18, the doc recommends errors.Is(err, fs.ErrNotExist) rather than errors.Is(err, os.ErrNotExist); hence the doc update.

Update doc to use fs.ErrNotExist

---

mount/go.mod
mount/go.sum
mountinfo/go.mod
mountinfo/go.sum
mountinfo/mountinfo_freebsdlike.go
mountinfo/mountinfo_openbsd.go
signal/go.mod
signal/go.sum
symlink/go.mod
symlink/go.sum

A newer version of x/sys/unix updates the OpenBSD bindings
which makes the `int8SliceToString` helper function obsolete.
This change updates the x/sys/unix version

Bump x/sys/unix

---

.github/workflows/test.yml
Makefile

This step should fail if a PR author bumped or added some dependencies,
or bumped go version in `go.mod`, but forgot to run `go mod tidy`.
Inspired by https://github.com/moby/sys/pull/118#discussion_r890371395

ci: add go mod tidy check

---

mount/go.mod
mount/go.sum

Release notes: https://github.com/moby/sys/releases/tag/mountinfo%2Fv0.6.2

mount: bump mountinfo to v0.6.2

---

Makefile
sequential/doc.go
sequential/go.mod
sequential/go.sum
sequential/sequential_unix.go
sequential/sequential_windows.go

Integrating the "Sequential" utilities from [github.com/docker/docker/pkg/system](https://github.com/moby/moby/tree/3e8573a85a42d4882068bffab7d83f5d93d417e1/pkg/system),
taken from commit [3e8573a85a42d4882068bffab7d83f5d93d417e1](https://github.com/moby/moby/commit/3e8573a85a42d4882068bffab7d83f5d93d417e1)
Steps taken:
cd ~/Projects
git clone https://github.com/docker/docker.git moby_sys
cd moby_sys
git rev-parse --verify HEAD
3e8573a85a42d4882068bffab7d83f5d93d417e1
git filter-repo \
--path-glob 'pkg/system/filesys_*.go' \
--path-rename pkg/system/filesys_unix.go:sequential/sequential_unix.go \
--path-rename pkg/system/filesys_windows.go:sequential/sequential_windows.go
cd ~/go/src/github.com/moby/sys
git checkout -b integrate_moby_sequential
git remote add …

Integrate github.com/docker/docker/pkg/system Sequential utilities

---

sequential/sequential_windows.go

- relates to https://github.com/moby/moby/pull/44282
Replace it with the const that's now defined in golang.org/x/sys/windows

sequential: remove fileFlagSequentialScan const

---

sequential/sequential_unix.go
sequential/sequential_windows.go

Don't mix-and-mash packages for consts.
Move the error-handling to openFileSequential and update exported functions to use openFileSequential instead of OpenFile().
The non-Windows implementations are aliases for the "os" stdlib package equivalents. This patch removes the local documentation, as it was out of date for some, and having the local documentation could give the impression that these functions were anything other than an alias.
Update the docs to refer to the "os" stdlib equivalents, and describe the changes compared to those, instead of replicating the os package's documentation.

sequential: refactor, and update godoc

---

.gitignore

When running golangci-lint locally (make lint), it compiles the golangci-lint binary in BINDIR, which defaults to _build/bin inside the repository.

add _build to gitignore

---

Makefile
user/go.mod
user/go.sum
user/lookup_unix.go
user/user.go
user/user_fuzzer.go
user/user_test.go

- alternative to https://github.com/moby/sys/pull/132
- closes https://github.com/moby/sys/pull/132
- relates to / addresses https://github.com/opencontainers/runc/issues/3998
-----
This integrate the github.com/opencontainers/runc/libcontainer/user package
at commit [opencontainers/runc@a3a0ec48c464fe6458d2ba067f6707c027e5384e].
This package was originally authored in a "utils" package in the Docker
repository, after which moved to "libcontainer", which became part of runc.
Some commits were not included in history, due to them being applied in
the Docker repository before moving into "libcontainer". Leaving links
to those for future reference:
- [docker/docker@eb38750]
- [docker/docker@e41507b]
- [docker/docker@b07314e]
[opencontainers/runc@a3a0ec48c464fe6458d2ba067f6707c027e5384e]: …

integrate github.com/opencontainers/runc/libcontainer/user (alternative)

---

mountinfo/mountinfo_linux.go

In a Go program with many threads, which goroutine is running on the thread-group leader thread is not something programs can controls. Thus, even if you use runtime.LockOSThread() for threads that have different mount namespaces, it's possible that /proc/self will refer to the "wrong" thread.
The solution is to simply use /proc/thread-self, which will always provide the correct result for the calling thread.
The usage of /proc/self/mountinfo caused isuses for a patch to runc which creates a thread to create id-mapped mounts (which requires joining the container mount namespace).
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

mountinfo: linux: use /proc/thread-self/mountinfo

---

mountinfo/mountinfo_linux.go

In very specific cases (that we hit in runc), it is possible to be running in a child pid namespace (where the Go process's pid is 1) but still have a host /proc. While this is not a problem with /proc/thread-self (since the process *is* in the host pid namespace), the /proc/self/task/<tid> fallback doesn't work because gettid(2) returns the wrong thread-id for the host pid namespace.
There isn't much we can do in this case other than use /proc/self, because the simple workarounds (grep NSpid /proc/self/task/*/status) aren't available in pre-3.17 kernels and any more complicated schemes (such as setting the signal mask to something unique and scanning for it) are unworkable for obvious reasons.
Fixes: 12c61a3e3acb ("mountinfo: linux: use /proc/thread-self/mountinfo")
Signed-off-by: Aleksa …

mountinfo: linux: add a /proc/self/mountinfo fallback

---

.github/workflows/test.yml
Makefile
mount/go.mod
mount/go.sum
mount/mount_unix.go
mountinfo/go.mod
mountinfo/go.sum
sequential/go.mod
sequential/go.sum
sequential/sequential_windows.go
signal/go.mod
signal/go.sum
symlink/go.mod
symlink/go.sum

1. Bump Go to supported version, other CI components.
2. Bump go to 1.17 in */go.mod.
3. Bump golang.org/x/sys to ~~v0.11.0.~~ v.0.1.0.
4. mount: fix an errorlint issue with Go 1.20+.
5. mount: rm unneeded errorlint annotations (thanks to https://github.com/polyfloyd/go-errorlint/pull/47).
6. sequential: fix a formatting issue (file is not gofumpt'ed)

Bump CI to use supported go version, fix a single Go 1.20 issue in mount pkg; rm uneeded errorlint annotations

---

.github/workflows/test.yml
Makefile
mountinfo/mounted_linux.go
user/user.go

- follow-up https://github.com/moby/sys/pull/129#issuecomment-2205339496
From the GitHub actions documentation [1];
> The macos-11 label has been deprecated and will no longer be available
> after 28 June 2024.
[1]: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
Upgrades Node.js runtime from node16 to node20
Only a single commit is fetched by default, for the ref/SHA that triggered
the workflow. Set fetch-depth: 0 to fetch all history for all branches and
tags.
Commit d6a52098207d17e40c2247f7893626b5e07045f5 removed most errorlint
annotations, with one remaining.
golangci-lint v1.59.1 comes with errorlint v1.5.2, which contains
the fix [2] whitelisting all errno …

ci/gha: add Go 1.22, update various actions, add macos-12, ubuntu-24.04

---

symlink/README.md
symlink/doc.go
symlink/fs.go
symlink/fs_windows.go

- fixes https://github.com/moby/sys/issues/58
- Fix references to EvalSymlinksInScope, which is non-exported
- Add relevant links to original implementation / introduction of the code to allow comparing the fork with the original upstream code.
- Move GoDoc from the non-exported evalSymlinksInScope function to the exported FollowSymlinkInScope.
- Remove the README.md, instead using doc.go to provide the package description.

symlink: touch-up documentation

---

mount/go.mod
mount/go.sum

full diff: https://github.com/moby/sys/compare/mountinfo/v0.6.2...mountinfo/v0.7.2

mount: bump github.com/moby/sys/mountinfo v0.7.2

---

.github/workflows/test.yml
mount/flags_unix.go
mount/go.mod
mount/mounter_linux_test.go
mountinfo/go.mod
mountinfo/mountinfo_linux.go
sequential/go.mod
signal/go.mod
symlink/go.mod
user/go.mod

This allows us to start using some new features, like strings.Cut
it's faster, and uses less allocations.
It's faster, and reduces 410 allocations (1976 -> 1566).
Before:
go test -v -test.benchmem -count=10 -run ^$ -bench BenchmarkParseMountinfo .
go: downloading golang.org/x/sys v0.1.0
goos: linux
goarch: arm64
pkg: github.com/moby/sys/mountinfo
BenchmarkParseMountinfo
BenchmarkParseMountinfo-10        4405    283442 ns/op  245426 B/op    1976 allocs/op
BenchmarkParseMountinfo-10        4180    258441 ns/op  245425 B/op    1976 allocs/op
BenchmarkParseMountinfo-10        4146    258770 ns/op  245425 B/op    1976 allocs/op
BenchmarkParseMountinfo-10        4180    259924 ns/op  245425 B/op    1976 allocs/op
BenchmarkParseMountinfo-10        4162    263537 ns/op  245425 B/op    1976 …

update to go1.18, and use strings.Cut

---

mountinfo/mountinfo_linux.go
mountinfo/mountinfo_linux_test.go

This is an alternative to #143.
It has been pointed out that unescape implementation is unnecessarily
complex, and I tend to agree. Plus, we never expect any errors during
unescaping, and if there are any, we can always return the string as is.
So, drop the error return, and simplify the algorithm. Modify the test
case and the benchmark accordingly.
NOTE this also fixes the issue of trying to convert escape sequences
where the character code is >= `utf8.RuneSelf` (128 decimal, 0200 octal).
Adding those to the output may result in invalid utf-8 strings. The new
code doesn't try to unescape those (and the tests are amended to check
that).
Add some more test cases.
Here's benchstat output:
```
name               old time/op    new time/op    delta
Unescape-20           851ns ± 1%     358ns ± …
```

mountinfo: simpify, speedup, and fix unescape

---

.github/workflows/test.yml
Makefile
mount/flags_bsd.go
mount/flags_unix.go
mount/mount_errors.go
mount/mount_unix.go
mount/mount_unix_test.go
mount/mounter_freebsd.go
mount/mounter_openbsd.go
mount/mounter_unsupported.go
mountinfo/mounted_unix.go
mountinfo/mountinfo_bsd.go
mountinfo/mountinfo_freebsdlike.go
mountinfo/mountinfo_test.go
mountinfo/mountinfo_unsupported.go
sequential/sequential_unix.go
signal/signal_linux.go
signal/signal_linux_mipsx.go
signal/signal_linux_test.go
signal/signal_unix.go
signal/signal_unsupported.go
symlink/fs_unix.go
symlink/fs_unix_test.go

This removes old (Go < 1.17) build tags, and makes sure CI runs `go fix` (which, unfortunately, is not part of any linter).

Add go fix to CI, rm old build tags

---

.github/workflows/test.yml
Makefile

Add Go 1.23, drop 1.21.
Also, bump golangci-lint to v1.60.1 (which adds Go 1.23 support).
A draft pending #144 merge.

Add Go 1.23, drop 1.21, bump golangci-lint

---

capability/CHANGELOG.md
capability/README.md
capability/capability.go

Assorted doc improvements:
* doc: add cross-references;
* doc: use tabs in code examples;
* README: add link to changelog;
* CHANGELOG: link to 0.2.0 release.

capability: doc improvements

---

capability/capability.go
capability/capability_linux.go
capability/capability_noop.go
capability/capability_test.go

So that the code which uses capability.LastCap can be compiled on
non-Linux platforms.
Found the issue while working on https://github.com/containers/common/pull/2167

capability: add LastCap stub for non-Linux

---

.github/workflows/test.yml

ci: fix not honoring PACKAGES setting in gha Windows runners

---

capability/CHANGELOG.md

Add 0.3.0 changelog and release date.

capability: prepare for v0.3.0 release 

---

.github/workflows/test.yml

_This is an alternative to #155._
----
First, checking out the code should be done before installing Go.
Second, since we don't have top-level `go.mod`, actions/setup-go complains:
> Restore cache failed: Dependencies file is not found in /home/runner/work/sys/sys. Supported file pattern: go.sum
One way to solve this would be to add
```yml
cache-dependency-path: "*/go.sum"
```
parameter to `actions/setup-go`. Alas it won't work because not all modules here have go.mod, and * in GHA is not what you think it is (i.e. not a part of shell glob pattern, but rather "every directory"), and as a result it complains about missing go.sum files.
Another way is to list all the paths explicitly, which is not good from the maintainability perspective (someone will definitely forgot to add a go.sum …

ci: checkout first, disable go caching

---

capability/capability_linux.go
capability/capability_test.go

See individual commits for details. Originally part of #159.

capability: use strings.CutPrefix; test improvements

---

capability/capability_test.go

See commits for details.
@lifubang PTAL

capability: test improvements

---

capability/capability_test.go

Houston, we have a problem:
```
$ go test -exec sudo -run AmbientCapSet -count 3 -v
=== RUN   TestAmbientCapSet
--- PASS: TestAmbientCapSet (0.00s)
=== RUN   TestAmbientCapSet
capability_test.go:113: The test needs `CAP_SETPCAP`.
--- SKIP: TestAmbientCapSet (0.00s)
=== RUN   TestAmbientCapSet
capability_test.go:113: The test needs `CAP_SETPCAP`.
--- SKIP: TestAmbientCapSet (0.00s)
PASS
ok  	github.com/moby/sys/capability	0.024s
```
The solution is, tests that manipulate capabilities should be run in a separate process.
Add a helper to do just that, and modify `TestAmbientCapSet `to use it. In particular, the child needs to call `os.Exit` (which it does directly, in the end, and also indirectly, via `log.Fatal`).

capability: add/use testInChild helper

---

Makefile

When running make test, there appears an error:
/bin/sh: 1: test: go test -exec sudo: unexpected operator
or
/bin/sh: line 1: test: go test -exec sudo: binary operator expected
(depending on which shell is used).
This is caused by CMD value containing extra quotes (from RUN_VIA_SUDO=-exec "sudo -n") which test sees as an extra option.
Enclose test argument in single quotes to fix the issue.

Makefile: fix error from test

---

capability/capability_linux.go
capability/capability_test.go

Current version of `capsV3.Apply` has a major problem: if you do something like this:
```go
c, err := capability.NewPid(pid)
...
c.Set(capability.AMBIENT, capability.CAP_CHOWN)
c.Apply(capability.AMBIENT)
```
then the ambient capability will be applied to the current process, rather than the process identified by pid. Same issue for `BOUNDS`.
For `CAPS` the situation is slightly different: `capset(2)` man page says:
> EPERM	The caller attempted to use capset() to modify the capabilities
> 	of a thread other than itself, but lacked sufficient privilege.
> 	For kernels supporting VFS capabilities, this is never permitted.
Here _kernels supporting VFS capabilities_ means most kernels >= v2.6.24, and all kernels >= v2.6.33. Since Go 1.18+ only supports Linux >= v2.6.32, this pretty much means …

capability: Apply: deny for another process

---

.github/workflows/test.yml
capability/.codespellrc
capability/enum.go
signal/signal.go
symlink/fs.go

Fix typos, rename some variables etc, add codespell job to CI.
Please see individual commits for details.
~~_Currently a draft pending #162 merge._~~

ci: add codespell

---

capability/capability.go
capability/capability_linux.go
capability/capability_noop.go
capability/capability_test.go
capability/syscall_linux.go

The API being added is the same as in [kernel.org/pub/linux/libs/security/libcap/cap](https://pkg.go.dev/kernel.org/pub/linux/libs/security/libcap/cap)
package, although the implementation is a bit simpler (here we only set
capabilities for the calling thread).
With this, we can switch runc to moby/sys/capability.
Co-authored-by: @lifubang 
Closes: #165

capability: add separate ambient and bound API

---

capability/CHANGELOG.md

Copy-pasted below so we can check the markup. Note some links won't work until a release is made.
----
* New separate API for ambient ([GetAmbient], [SetAmbient], [ResetAmbient])
and bound ([GetBound], [DropBound]) capabilities, modelled after libcap. (#176)
* [Apply] now returns an error if called for non-zero `pid`. Before this change,
it could silently change some capabilities of the current process, instead of
the one identified by the `pid`. (#168, #174)
* Fixed tests that change capabilities to be run in a separate process. (#173)
* Other improvements in tests. (#169, #170)
* Use raw syscalls (which are slightly faster). (#176)
* Most tests are now limited to testing the public API of the package. (#162)
* Simplify parsing /proc/*pid*/status, add a test case. (#162)
* Optimize the …

capability: v0.4.0 release changelog

---

.github/workflows/test.yml
Makefile
reexec/go.mod
reexec/reexec.go
reexec/reexec_linux.go
reexec/reexec_other.go
reexec/reexec_test.go

- relates to https://github.com/moby/moby/issues/32989
This integrates the reexec package from moby at commit;
cc1d50a63daa725dfb8d43bba7c259107fbb9f74 ([1]).
Migration was done using the following steps:
```bash
cd ~/Projects
git clone https://github.com/moby/moby.git moby_temp
cd moby_temp
git rev-parse --verify HEAD
cc1d50a63daa725dfb8d43bba7c259107fbb9f74
git filter-repo --analyze
git filter-repo \
--path 'pkg/reexec' \
--path-rename pkg/reexec:reexec
cd ~/go/src/github.com/moby/sys
git checkout -b integrate_reexec
git remote add moby_temp ~/Projects/moby_temp
git fetch moby_temp
git merge --allow-unrelated-histories --signoff -S moby_temp/master
```
[1]: https://github.com/moby/moby/commit/cc1d50a63daa725dfb8d43bba7c259107fbb9f74

integrate pkg/reexec

---

user/idtools.go
user/idtools_unix.go
user/idtools_unix_test.go
user/idtools_windows.go

Merges the idtools package functionality from github.com/moby/moby/pkg/idtools into the user package. The package was previously trimmed down and is simplified further to better fit `moby/sys`.
Now the package interface will just expand with:
- `MkdirAllAndChown` with  `WithOnlyNew` as a `MkdirOpt`
- `MkdirAndChown` also supporting the opts
- `IdentityMapping` its functions `RootPair`, `ToHost`, `ToContainer`, `Empty`
Note the `Identity` type is gone since `SID` was not used in the package or by any of the functions. It is more common to just pass along the uid and gid.

Merge functionality from `github.com/moby/moby/pkg/idtools` into `user`

---

.github/workflows/test.yml
Makefile
atomicwriter/atomicwriter.go
atomicwriter/atomicwriter_test.go
atomicwriter/go.mod
atomicwriter/go.sum

- relates to https://github.com/moby/moby/pull/49608
- relates to https://github.com/moby/moby/issues/32989
This integrates the atomicwriter package from moby at commit;
[d7b743b8569e253b61ea8d70e75146ff35d50417][1].
Migration was done using the following steps:
```bash
cd ~/Projects
git clone https://github.com/moby/moby.git moby_temp
cd moby_temp
git rev-parse --verify HEAD
d7b743b8569e253b61ea8d70e75146ff35d50417
git filter-repo --analyze
git filter-repo \
--path 'pkg/ioutils/fswriters.go' \
--path 'pkg/ioutils/fswriters_test.go' \
--path 'pkg/atomicwriter' \
--path-rename pkg/atomicwriter:atomicwriter
cd ~/go/src/github.com/moby/sys
git checkout -b integrate_atomicwriter
git remote add moby_temp ~/Projects/moby_temp
git fetch moby_temp
git merge …
```

integrate pkg/atomicwriter

---

capability/syscall_linux.go
mountinfo/mounted_linux_test.go
user/user.go

- relates to https://github.com/moby/sys/pull/186
We could suppress this linter, as using w.File.xxx makes it slightly more explicit, but probably fine as well.
```
Error: atomicwriter/atomicwriter.go:205:11: QF1008: could remove embedded field "File" from selector (staticcheck)
err := w.File.Sync()
^
```
```
Error: mountinfo/mounted_linux_test.go:282:6: QF1001: could apply De Morgan's law (staticcheck)
if !(tc.isNotExist && errors.Is(err, os.ErrNotExist)) {
^
Error: mountinfo/mounted_linux_test.go:353:8: QF1001: could apply De Morgan's law (staticcheck)
if !(tc.isNotExist && errors.Is(err, os.ErrNotExist)) {
^
```
```
Error: capability/syscall_linux.go:144:2: QF1003: could use tagged switch on data.version (staticcheck)
if data.version == 1 {
^
```
```
Error: user/user.go:447:16: ST1005: …
```

fix linting issues for golangci-lint v2

---

.golangci.yml

This is a followup to #186.
This repo:
- does not have any paths that are excluded;
- does not have any generated code.
Also, neither "common-false-positives" nor "legacy" presets suppress
any warnings, so remove those as well.

.golangci.yml: remove unused exceptions

---

reexec/reexec.go
reexec/reexec_linux.go
reexec/reexec_other.go
reexec/reexec_test.go

- follow-up to / stacked on https://github.com/moby/sys/pull/191
Adds a CommandContext command, to provide the equivalent of exec.CommandContext.

reexec: add "CommandContext"

---

.github/workflows/test.yml
Makefile

- supersedes, closes https://github.com/moby/sys/pull/196
Some modules require a more recent version of Go and must be skipped in tests. Previously we manually kept a list, but we can detect the version of Go that's required from the go.mod.

gha: skip modules on unsupported Go versions, test against 1.18.x, oldstable, stable

---

.github/workflows/test.yml
.gitignore
Makefile

First, let's not install golangci-lint from Makefile, instead relying on whatever version a developer already has installed and available.
Second, we still need golangci-lint in GHA CI. For that, let's use golangci-lint-action. Unfortunately, there's no way to NOT run it from the action, or run it on multiple directories (see [1]), so run it on a single module.
This is better for CI because we use all the good bits from the golangci-lint-action (caching and annotations).
While at it, bump golangci-lint from v2.0.3 to v2.4.x.
[1]: https://github.com/golangci/golangci-lint-action/issues/1226

ci: don't install private golangci-lint; bump to v2.4
